<a href="https://colab.research.google.com/github/Fodhe-bot/Json-beginers/blob/main/data_cleaned.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd # Import Pandas

In [ ]:
from google.colab import files
uploaded = files.upload()  # Select a file to upload

df = pd.read_csv("/content/bank_loan.csv")  # Read the file into Pandas
df.head()  # Show the first 5 rows

Saving bank_loan.csv to bank_loan (1).csv

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
0,1,25,1,49,91108,4,1/60,1,0,0,1,0,0,0
1,2,45,19,34,90089,3,1/50,1,0,0,1,0,0,0
2,3,39,15,11,94720,1,1/00,1,0,0,0,0,0,0
3,4,35,9,100,94112,1,2/70,2,0,0,0,0,0,0
4,5,35,8,45,91330,4,1/00,2,0,0,0,0,0,1

In [ ]:
df.info()      # Column names, data types, and missing values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  5000 non-null   int64
 1   Age                 5000 non-null   int64
 2   Experience          5000 non-null   int64
 3   Income              5000 non-null   int64
 4   ZIP Code            5000 non-null   int64
 5   Family              5000 non-null   int64
 6   CCAvg               5000 non-null   object
 7   Education           5000 non-null   int64
 8   Mortgage            5000 non-null   int64
 9   Personal Loan       5000 non-null   int64
 10  Securities Account  5000 non-null   int64
 11  CD Account          5000 non-null   int64
 12  Online              5000 non-null   int64
 13  CreditCard          5000 non-null   int64
dtypes: int64(13), object(1)
memory usage: 547.0+ KB

In [ ]:
df.head()

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
0,1,25,1,49,91108,4,1/60,1,0,0,1,0,0,0
1,2,45,19,34,90089,3,1/50,1,0,0,1,0,0,0
2,3,39,15,11,94720,1,1/00,1,0,0,0,0,0,0
3,4,35,9,100,94112,1,2/70,2,0,0,0,0,0,0
4,5,35,8,45,91330,4,1/00,2,0,0,0,0,0,1

In [ ]:
print(df.isnull().sum())

ID                    0
Age                   0
Experience            0
Income                0
ZIP Code              0
Family                0
CCAvg                 0
Education             0
Mortgage              0
Personal Loan         0
Securities Account    0
CD Account            0
Online                0
CreditCard            0
dtype: int64

In [ ]:
print(df.describe())

                ID          Age   Experience       Income      ZIP Code  \
count  5000.000000  5000.000000  5000.000000  5000.000000   5000.000000
mean   2500.500000    45.338400    20.104600    73.774200  93152.503200
std    1443.520003    11.463166    11.467954    46.033729   2121.852005
min       1.000000    23.000000    -3.000000     8.000000   9307.000000
25%    1250.750000    35.000000    10.000000    39.000000  91911.000000
50%    2500.500000    45.000000    20.000000    64.000000  93437.000000
75%    3750.250000    55.000000    30.000000    98.000000  94608.000000
max    5000.000000    67.000000    43.000000   224.000000  96651.000000

            Family    Education     Mortgage  Personal Loan  \
count  5000.000000  5000.000000  5000.000000    5000.000000
mean      2.396400     1.881000    56.498800       0.096000
std       1.147663     0.839869   101.713802       0.294621
min       1.000000     1.000000     0.000000       0.000000
25%       1.000000     1.000000     0.000000       0.000000
50%       2.000000     2.000000     0.000000       0.000000
75%       3.000000     3.000000   101.000000       0.000000
max       4.000000     3.000000   635.000000       1.000000

       Securities Account  CD Account       Online   CreditCard
count         5000.000000  5000.00000  5000.000000  5000.000000
mean             0.104400     0.06040     0.596800     0.294000
std              0.305809     0.23825     0.490589     0.455637
min              0.000000     0.00000     0.000000     0.000000
25%              0.000000     0.00000     0.000000     0.000000
50%              0.000000     0.00000     1.000000     0.000000
75%              0.000000     0.00000     1.000000     1.000000
max              1.000000     1.00000     1.000000     1.000000

In [ ]:
# Select rows where Experience is negative and set them to 0
df.loc[df['Experience'] < 0, 'Experience'] = 0

# Verify the fix
print(f"New minimum experience: {df['Experience'].min()}")

New minimum experience: 0

In [ ]:
print(df.describe())

                ID          Age   Experience       Income      ZIP Code  \
count  5000.000000  5000.000000  5000.000000  5000.000000   5000.000000
mean   2500.500000    45.338400    20.119600    73.774200  93152.503200
std    1443.520003    11.463166    11.440484    46.033729   2121.852005
min       1.000000    23.000000     0.000000     8.000000   9307.000000
25%    1250.750000    35.000000    10.000000    39.000000  91911.000000
50%    2500.500000    45.000000    20.000000    64.000000  93437.000000
75%    3750.250000    55.000000    30.000000    98.000000  94608.000000
max    5000.000000    67.000000    43.000000   224.000000  96651.000000

            Family    Education     Mortgage  Personal Loan  \
count  5000.000000  5000.000000  5000.000000    5000.000000
mean      2.396400     1.881000    56.498800       0.096000
std       1.147663     0.839869   101.713802       0.294621
min       1.000000     1.000000     0.000000       0.000000
25%       1.000000     1.000000     0.000000       0.000000
50%       2.000000     2.000000     0.000000       0.000000
75%       3.000000     3.000000   101.000000       0.000000
max       4.000000     3.000000   635.000000       1.000000

       Securities Account  CD Account       Online   CreditCard
count         5000.000000  5000.00000  5000.000000  5000.000000
mean             0.104400     0.06040     0.596800     0.294000
std              0.305809     0.23825     0.490589     0.455637
min              0.000000     0.00000     0.000000     0.000000
25%              0.000000     0.00000     0.000000     0.000000
50%              0.000000     0.00000     1.000000     0.000000
75%              0.000000     0.00000     1.000000     1.000000
max              1.000000     1.00000     1.000000     1.000000

In [ ]:
# Convert CCAvg to numeric, turning errors into NaNs
df['CCAvg'] = pd.to_numeric(df['CCAvg'], errors='coerce')

# Check if any NaNs were created by the conversion
print(f"Missing values in CCAvg: {df['CCAvg'].isnull().sum()}")

Missing values in CCAvg: 5000

In [ ]:
# 1. Force the column to be strings again
# 2. Replace the slash with a dot
# 3. Convert to numeric properly
df['CCAvg'] = df['CCAvg'].astype(str).str.replace('/', '.').astype(float)

# 4. Check the results
print(df['CCAvg'].head())
print(f"Missing values now: {df['CCAvg'].isnull().sum()}")

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: CCAvg, dtype: float64
Missing values now: 5000

In [ ]:
# 1. Reload (Make sure to use your actual file name)
df = pd.read_csv('/content/bank_loan.csv')

# 2. Clean the 'Experience' first (since we know it's a problem)
df.loc[df['Experience'] < 0, 'Experience'] = 0

# 3. Clean the 'CCAvg' slashes while they are still strings
df['CCAvg'] = df['CCAvg'].str.replace('/', '.')

# 4. NOW convert to numeric
df['CCAvg'] = pd.to_numeric(df['CCAvg'], errors='coerce')

# 5. Final check
print(df['CCAvg'].head())
print(f"Success! Missing values: {df['CCAvg'].isnull().sum()}")

0    1.6
1    1.5
2    1.0
3    2.7
4    1.0
Name: CCAvg, dtype: float64
Success! Missing values: 0

In [ ]:
# 1. Convert to string and pad with zeros to ensure 5 digits
df['ZIP Code'] = df['ZIP Code'].astype(str).str.zfill(5)

# 2. Check a few to make sure it worked
print(df['ZIP Code'].head())

# 3. Check the type (it should now say 'object')
print(df['ZIP Code'].dtype)

0    91108
1    90089
2    94720
3    94112
4    91330
Name: ZIP Code, dtype: object
object

In [ ]:
# Compare the average income for each education level
print(df.groupby('Education')['Income'].mean())

Education
1    85.586355
2    64.313614
3    66.122585
Name: Income, dtype: float64

In [ ]:
print(df['Education'].value_counts())

Education
1    2096
3    1501
2    1403
Name: count, dtype: int64

In [ ]:
df.to_csv('bank_loan_cleaned.csv', index=False)